spring.application.name=book-my-show
spring.datasource.url=jdbc:postgresql://localhost:5432/book-my-show
spring.datasource.username=postgres
spring.datasource.password=Hrishi@123
spring.jpa.hibernate.ddl-auto=update
